# Nome da aplicação
spring.application.name=baozistore
# ===================================
# CONFIGURAÇÃO DO BANCO H2
# ===================================
# Habilita o console web do H2 (acessível no navegador)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
# Configurações da fonte de dados (datasource)
# Habilita o console web do H2 (acessível em arquivo na pasta raiz)
spring.datasource.url=jdbc:h2:file:./h2-database
spring.datasource.username=sa
spring.datasource.password=
# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
